# Generated by Django 5.2 on 2025-05-09 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='assigned_user',
        ),
        migrations.AddField(
            model_name='todo',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
